main/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('resizer.urls')),
]

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

resizer/urls.py
from django.urls import path

from . import views


app_name = 'resizer'

urlpatterns = [
    path('', views.home, name='home'),
    path('upload/', views.UploadAndResizeView.as_view(), name='upload'),
    path('status/', views.CheckStatusView.as_view(), name='check_status'),
    path('status/<str:task_id>/', views.TaskStatusView.as_view(), name='task'),
]

resizer/models.py
from django.db import models


# Create your models here.
class ProcessedTasks(models.Model):
    task_id = models.CharField(max_length=100, blank=False)

resizer/forms.py
from django import forms


VALID_FORMATS = ['jpeg', 'jpg', 'png']
IMAGE_DIMENSIONS = {
    'height': {
        'min': 1,
        'max': 9999,
    },
    'width': {
        'min': 1,
        'max': 9999,
    },
}
MAX_FILE_SIZE_MB = 3 # 3 MB default
MAX_FILE_SIZE = MAX_FILE_SIZE_MB * 2**20 


class ImageUploadForm(forms.Form):

    image = forms.ImageField(required=True)
    width = forms.IntegerField(
        min_value=IMAGE_DIMENSIONS['width']['min'],
        max_value=IMAGE_DIMENSIONS['width']['max'],
        label=f"Width ({IMAGE_DIMENSIONS['width']['min']} - {IMAGE_DIMENSIONS['width']['max']} px)"
    )
    height = forms.IntegerField(
        min_value=IMAGE_DIMENSIONS['height']['min'],
        max_value=IMAGE_DIMENSIONS['height']['max'],
        label=f"Height ({IMAGE_DIMENSIONS['height']['min']} - {IMAGE_DIMENSIONS['height']['max']} px)"
    )

    # checking for valid image formats
    def clean_image(self):
        image = self.cleaned_data['image']
        image_format = image.name.split('.')[-1].lower()
        if image_format not in VALID_FORMATS:
            raise forms.ValidationError(
                f'Error: the image must be in one of the following formats: {", ".join(VALID_FORMATS)}.'
            )
        if image.size > MAX_FILE_SIZE:
            raise forms.ValidationError(f'Error: the image size exceeds {MAX_FILE_SIZE_MB} MB.')
        return image


class CheckTaskByIDForm(forms.Form):
    
    task_id = forms.CharField(label='Task ID:', required=True)

resizer/views.py
import os

from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.core.files.storage import default_storage
from django.core.files.base import File
from django.conf import settings
from django.contrib import messages
from celery import current_app
from django.http import HttpResponseRedirect

from .forms import ImageUploadForm, CheckTaskByIDForm
from .tasks import resize_image_task
from .models import ProcessedTasks


# Create your views here.
class UploadAndResizeView(View):

    def get(self, request):
        form = ImageUploadForm()
        return render(request, 'resizer/upload.html', {'form': form})

    def post(self, request):
        form = ImageUploadForm(request.POST, request.FILES)
        context = {}
        if form.is_valid():
            image = File(request.FILES['image'])
            path = default_storage.save(f'tmp/{image.name}', image)
            path = os.path.join(settings.MEDIA_ROOT, path)
            task = resize_image_task.delay(
                image=path,
                width=int(request.POST['width']),
                height=int(request.POST['height']),
            )
            context['task_id'] = task.id
            context['task_status'] = task.status
            if task.status == 'PENDING':
                context['task_status'] = 'BEING PROCESSED'
            ProcessedTasks.objects.create(task_id=task.id)
            return render(request, 'resizer/check_status.html', context)
        context['form'] = form
        return render(request, 'resizer/upload.html', context)


class CheckStatusView(View):

    def get(self, request):
        form = CheckTaskByIDForm()
        return render(request, 'resizer/check_status.html', {'form': form})

    def post(self, request):
        form = CheckTaskByIDForm(request.POST)
        if form.is_valid():
            try:
                db_task_id = ProcessedTasks.objects.get(task_id=request.POST['task_id'])
                return HttpResponseRedirect(
                    reverse_lazy('resizer:task', kwargs={'task_id': request.POST['task_id']})
                )
            except:
                messages.error(request, f"Error: Image with ID: {request.POST['task_id']} does not exist.")
                return render(request, 'resizer/check_status.html', {'form': form})


class TaskStatusView(View):
    
    def get(self, request, task_id):
        task = current_app.AsyncResult(task_id)
        context = {
            'task_status': task.status,
            'task_id': task.id
        }
        if task.status == 'SUCCESS':
            context['resized_image_path'] = task.get()
        if task.status == 'PENDING':
            context['task_status'] = 'BEING PROCESSED'
        return render(request, 'resizer/check_status.html', context)


def home(request):
    return render(request, 'resizer/home.html')

resizer/templates/resizer/check_status.html
{% extends "resizer/home.html" %}


{% block content %}
    {% if not task_id %}
        <h2>Check status of your Task</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            {% if messages %}
                {% for message in messages %}
                    <font color="red">{{ message }}</font>
                {% endfor %}
            {% endif %}
            <br>
            <button type="submit">Check</button>
        </form>
    {% else %}
        <h2>Your task ID: {{ task_id }}</h2>
        <h3>Status: {{ task_status }}</h3> <a href="{% url 'resizer:task' task_id %}">Refresh</a>
        {% ifequal task_status 'SUCCESS' %}
            <img src="{{ MEDIA_URL }}/{{ resized_image_path }}">   
        {% endifequal %}
    {% endif %}
{% endblock content %}

resizer/templates/resizer/home.html
<!DOCTYPE html>
<html>
<head>
    <title>
        Image resizer
    </title>
</head>
<body>
    <h1>Image resizer application</h1>
    <ul>
        <li><a href="{% url 'resizer:home' %}">Home</a></li>
        <li><a href="{% url 'resizer:upload' %}">Upload image</a></li>
        <li><a href="{% url 'resizer:check_status' %}">Status page</a></li>
    </ul>
    <div>
        {% block content %}{% endblock content %}
    </div>
</body>
</html>

resizer/templates/resizer/upload.html
{% extends "resizer/home.html" %}


{% block content %}
    <h2>Select file to upload:</h2>
    <form action="{% url 'resizer:upload' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Resize</button>
        <br>
        {% if task_id %}
            <h2>Task</h2>
            Task ID: {{ task_id }} <a href="{% url 'resizer:task' task_id %}">Check status</a>
        {% endif %}
    </form>
{% endblock content %}